# Generated by Django 2.0.4 on 2018-04-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_home',
            name='email',
        ),
    ]
