# Generated by Django 2.0.4 on 2018-04-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0002_remove_my_home_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_home',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='my_home',
            name='id',
        ),
        migrations.AddField(
            model_name='my_home',
            name='announcement',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='my_home',
            name='major',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='my_home',
            name='resource',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='my_home',
            name='studentNum',
            field=models.CharField(default='0', max_length=9),
        ),
        migrations.AddField(
            model_name='my_home',
            name='subject',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='my_home',
            name='userID',
            field=models.CharField(default='0', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='my_home',
            name='name',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
